MVC5-Proje1/Controllers/YazarlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_Proje1.Models.Entity;

namespace MVC5_Proje1.Controllers
{
    public class YazarlarController : Controller
    {
        MV5_Proje1Entities db = new MV5_Proje1Entities();
        // GET: Yazarlar
        public ActionResult Index()
        {
            var data = db.TBL_Yazar.ToList();   
            return View(data);
        }
        public ActionResult YazarSil(int id)
        {
            var data = db.TBL_Yazar.Find(id);
            db.TBL_Yazar.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Yazargetir(int id)
        {
            var x = db.TBL_Yazar.Find(id);
            return View("YazarGetir",x);
        }
        [HttpPost]
        public ActionResult YazarGuncelle(TBL_Yazar p)
        {
            var x = db.TBL_Yazar.Find(p.Yazarid);
            x.yazarad = p.yazarad;
            x.yazarsoyad = p.yazarsoyad;
            x.yazardetay = p.yazardetay;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }
        public ActionResult YazarEkle(TBL_Yazar p)
        {
            if(!ModelState.IsValid)
            {
                return View("YazarEkle");
            }
            db.TBL_Yazar.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarKitap(int id)
        {
            var x = db.TBL_Kitap.Where(k => k.Kitapyazar == id).ToList();
            var data1 = db.TBL_Yazar.Where(k => k.Yazarid==id).Select(z=>z.yazarad + " " + z.yazarsoyad).FirstOrDefault();
            ViewBag.d1 = data1;
            return View(x);
        }
    }
}

MVC5-Proje1/Views/Yazarlar/Index.cshtml
@using MVC5_Proje1.Models.Entity
@model List<TBL_Yazar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Yazar Tablosu</h2>
<br />
<table class="table table-hover">
    <tr style="background-color:rgb(207, 207, 207)">
        <th>Yazar ID</th>
        <th>Yazar ADI</th>
        <th>YAZAR SOYADI</th>
        <th>Detay</th>
        <th></th>
        <th></th>
        <th>Yazarın Kitapları</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Yazarid</td>
            <td>@x.yazarad</td>
            <td>@x.yazarsoyad</td>
            <td>@x.yazardetay</td>
            <td>@Html.ActionLink("Sil", "YazarSil", new { id = x.Yazarid }, new { @class = "btn btn-danger", onclick = "return confirm('SİLMEK İSTEDİĞİNE EMİN MİSİN?')" }) </td>
            <td><a href="/Yazarlar/YazarGetir/@x.Yazarid" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/Yazarlar/YazarKitap/@x.Yazarid" class="btn btn-warning">Kitaplar</a></td>
        </tr>
    }

</table>
<a href="/Yazarlar/Yazarekle/" class="btn btn-default" style="color:white; background-color:darkslategrey">Yeni Yazar Ekle</a>

MVC5-Proje1/Views/Yazarlar/YazarEkle.cshtml
@model MVC5_Proje1.Models.Entity.TBL_Yazar
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Yazar Ekleme Sayfası</h2>

<form class="form-group" method="post">
    <div>
        <div>
            <label>Yazar Adı</label>
            @Html.TextBoxFor(x => x.yazarad, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.yazarad) <br />
        </div>
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(x => x.yazarsoyad, new { @class = "form-control" }) <br />
        <label>Yazar Hakkında Detay</label>
        @Html.TextAreaFor(x => x.yazardetay, new { @class = "form-control" }) <br />
    </div>
    <div>
        <button class="btn btn-primary">Yazar Ekle</button>
    </div>

</form>

MVC5-Proje1/Views/Yazarlar/YazarKitap.cshtml
@using MVC5_Proje1.Models.Entity
@model List<TBL_Kitap>
@{
    ViewBag.Title = "YazarKitap";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<br />
<h2 style="color:red">@ViewBag.d1 Kitapları</h2>
<br />

<table class="table table-hover">
    <tr>
        <th>Kitap ID</th>
        <th>Kitap Adı</th>
        <th>Durum</th>
    </tr>
    @foreach (var x in Model)
    {
    <tr>
        <td>@x.Kitapid</td>
        <td>@x.Kitapad</td>
        <td>@x.Durum</td>
    </tr>

    }

</table>

MVC5-Proje1/Views/Yazarlar/Yazargetir.cshtml
@model MVC5_Proje1.Models.Entity.TBL_Yazar
@{
    ViewBag.Title = "Yazargetir";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Yazar Güncelleme Sayfası</h2>

@using (Html.BeginForm("YazarGuncelle","Yazarlar",FormMethod.Post))
{
<div class="form-group">
    <div style="margin-top:20px;"></div>
    <label>Yazar ID</label>
    @Html.TextBoxFor(X => X.Yazarid, new { @class = "form-control" })
    <br />
    <label>Yazar Adı</label>
    @Html.TextBoxFor(x => x.yazarad, new { @class = "form-control" })
    <br />
    <label>Yazar Soyadı</label>
    @Html.TextBoxFor(x => x.yazarsoyad, new { @class = "form-control" })
    <br />
    <label>Yazar Hakkında Detay</label>
    @Html.TextAreaFor(x => x.yazardetay, new { @class = "form-control" })
    <br />
</div>
<div>
    <button class="btn btn-primary" style="background-color:darkslategrey;color:white;" id="btn">Yazar Bilgisini Güncelle</button>
</div>
}