MVC5-Proje1/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_Proje1.Models.Entity;

namespace MVC5_Proje1.Controllers
{
    public class KitapController : Controller
    {
        MV5_Proje1Entities db = new MV5_Proje1Entities();
        // GET: Kitap

        public ActionResult Index(string p)
        {
            var x = from k in db.TBL_Kitap select k;
            if(!string.IsNullOrEmpty(p))
            {
                x = x.Where(m => m.Kitapad.Contains(p));
            }
          //var x = db.TBL_Kitap.ToList();
            return View(x.ToList());
        }

        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> x = (from i in db.TBL_Kategori.ToList()
                                      select new SelectListItem
                                      {
                                          Text = i.Ad,
                                          Value = i.Kategoriid.ToString()
                                      }).ToList();
            ViewBag.k = x;

            List<SelectListItem> yazar = (from i in db.TBL_Yazar.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.yazarad + ' ' + i.yazarsoyad,
                                              Value = i.Yazarid.ToString()
                                          }).ToList();
            ViewBag.yazar = yazar;

            return View();
        }

        [HttpPost]
        public ActionResult KitapEkle(TBL_Kitap p)
        {
            p.Durum = true;
            var kategori = db.TBL_Kategori.Where(x => x.Kategoriid == p.TBL_Kategori.Kategoriid).FirstOrDefault();
            var yazar = db.TBL_Yazar.Where(y => y.Yazarid == p.TBL_Yazar.Yazarid).FirstOrDefault();
            p.TBL_Kategori = kategori;
            p.TBL_Yazar = yazar;
            db.TBL_Kitap.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapSil(int id)
        {
            var x = db.TBL_Kitap.Find(id);
            db.TBL_Kitap.Remove(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult KitapGetir(int id)
        {
            List<SelectListItem> x = (from i in db.TBL_Kategori.ToList()
                                      select new SelectListItem
                                      {
                                          Text = i.Ad,
                                          Value = i.Kategoriid.ToString()
                                      }).ToList();
            ViewBag.k = x;

            List<SelectListItem> yazar = (from i in db.TBL_Yazar.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.yazarad + ' ' + i.yazarsoyad,
                                              Value = i.Yazarid.ToString()
                                          }).ToList();
            ViewBag.yazar = yazar;

            var data = db.TBL_Kitap.Find(id);
            return View(data);
        }
        [HttpPost]
        public ActionResult KitapGuncelle(TBL_Kitap p)
        {

            var x = db.TBL_Kitap.Find(p.Kitapid);
            x.Kitapad = p.Kitapad;
            x.Basımyıl = p.Basımyıl;
            x.Kitapsayfa = p.Kitapsayfa;
            x.Yayınevi = p.Yayınevi;
            x.Durum = p.Durum;
            var ktg = db.TBL_Kategori.Where(k => k.Kategoriid == p.TBL_Kategori.Kategoriid).FirstOrDefault();
            var yzr = db.TBL_Yazar.Where(y => y.Yazarid == p.TBL_Yazar.Yazarid).FirstOrDefault();
            x.Kitapkategori = ktg.Kategoriid;
            x.Kitapyazar = yzr.Yazarid;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
        
}

MVC5-Proje1/Views/Kitap/Index.cshtml
@using MVC5_Proje1.Models.Entity
@model List<TBL_Kitap>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>KİTAPLAR</h2>
<br />
@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{
    <br/>
     @Html.TextBox("p")
    <input type="submit" class="btn btn-warning" value="Ara" />
}
<br />

<form method="post">
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Kitap Adı</th>
            <th>Kitap Yazarı</th>
            <th>Kategorisi</th>
            <th>Basım Yılı</th>
            <th>Yayınevi</th>
            <th>Sayfa</th>
            <th>Durum</th>
            <th></th>
        </tr>
        @foreach (var x in Model)
        {
        <tr>
            <td>@x.Kitapid</td>
            <td>@x.Kitapad</td>
            <td>@x.TBL_Yazar.yazarad &nbsp;@x.TBL_Yazar.yazarsoyad</td>
            <td>@x.TBL_Kategori.Ad</td>
            <td>@x.Basımyıl</td>
            <td>@x.Yayınevi</td>
            <td>@x.Kitapsayfa</td>
            <td>@x.Durum</td>
            <td>@Html.ActionLink("Sil", "KitapSil", new { id = x.Kitapid }, new { @class = "btn btn-danger", onclick = "return confirm('SİLMEK İSTEDİĞİNE EMİN MİSİN?')" }) </td>
            <td><a href="/Kitap/KitapGetir/@x.Kitapid" class="btn btn-primary">Güncelle</a></td>
        </tr>
            }
    </table>
    <a href="/Kitap/KitapEkle" class="btn btn-primary">Kitap Ekle</a>
</form>

MVC5-Proje1/Views/Kitap/KitapEkle.cshtml
@model MVC5_Proje1.Models.Entity.TBL_Kitap
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Kitap Ekleme Sayfası</h2> <br />

<form class="form-group" method="post">
    <div>
        <label>Kitap Adı</label>
        @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control" })
        <br />
        <label>Kitap Kategorisi</label>
        @Html.DropDownListFor(x => x.TBL_Kategori.Kategoriid, (List<SelectListItem>)ViewBag.k, new { @class = "form-control" })
        <br />
        <label>Kitap Yazarı</label>
        @Html.DropDownListFor(x => x.TBL_Yazar.Yazarid, (List<SelectListItem>)ViewBag.yazar, new { @class = "form-control" })
        <br />
        <label>Kitap Basımyılı</label>
        @Html.TextBoxFor(x => x.Basımyıl, new { @class = "form-control" })
        <br />
        <label>Kitap Yayınevi</label>
        @Html.TextBoxFor(x => x.Yayınevi, new { @class = "form-control" })
        <br />
        <label>Kitap Sayfası</label>
        @Html.TextBoxFor(x => x.Kitapsayfa, new { @class = "form-control" })
        <br />
    </div>
    <button class="btn btn-primary">Kitabı Ekle</button>
 
</form>

MVC5-Proje1/Views/Kitap/KitapGetir.cshtml
@model MVC5_Proje1.Models.Entity.TBL_Kitap

    @{
        ViewBag.Title = "KitapGetir";
        Layout = "~/Views/Shared/Layout2.cshtml";
    }

    <h2>Kitap Güncelleme Sayfası</h2>

    @using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
    {
    <div class="form-group">
        <div style="margin-top:20px;"></div>
        <label>Kitap ID</label>
        @Html.TextBoxFor(x => x.Kitapid, new { @class = "form-control" })
        <br />
        <label>Kitap Adı</label>
        @Html.TextBoxFor(x => x.Kitapad, new { @class = "form-control" })
        <br />
        <label>Kategorisi</label>
        @Html.DropDownListFor(x => x.TBL_Kategori.Kategoriid, (List<SelectListItem>)ViewBag.k, new { @class = "form-control" })
        <br />
        <label>Yazar</label>
        @Html.DropDownListFor(x => x.TBL_Yazar.Yazarid, (List<SelectListItem>)ViewBag.yazar, new { @class = "form-control" })
        <br />
        <label>Basım Yılı</label>
        @Html.TextBoxFor(x => x.Basımyıl, new { @class = "form-control" })
        <br />
        <label>Yayın Evi</label>
        @Html.TextBoxFor(x => x.Yayınevi, new { @class = "form-control" })
        <br />
        <label>Sayfa</label>
        @Html.TextBoxFor(x => x.Kitapsayfa, new { @class = "form-control" })
        <br />
        <label>Durum</label>
        @Html.TextBoxFor(x=>x.Durum,new {@class="form-control" })
        <br />
    </div>
        <div>
            <button class="btn btn-primary" style="background-color:darkslategrey;color:white;" id="btn">Kitap Bilgisini Güncelle</button>
        </div>
    }