MVC5-Proje1/Controllers/DuyuruController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5_Proje1.Models.Entity;
namespace MVC5_Proje1.Controllers
{
    public class DuyuruController : Controller
    {
        MV5_Proje1Entities db = new MV5_Proje1Entities();

        public ActionResult Index()
        {
            var x = db.TBL_DUYURULAR.ToList();
            return View(x);
        }
        [HttpGet]
        public ActionResult DuyuruEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DuyuruEkle(TBL_DUYURULAR p )
        {
            db.TBL_DUYURULAR.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruDetay(int id)
        {
            var x = db.TBL_DUYURULAR.Find(id);
            var data1 = x.Kategori;
            ViewBag.d1 = data1;
            var data2 = x.icerik;
            ViewBag.d2 = data2;
            var data3 = x.Tarih;
            ViewBag.d3 = data3;
            return View(x);
        }
        public ActionResult DuyuruSil(int id)
        {
            var x = db.TBL_DUYURULAR.Find(id);
            db.TBL_DUYURULAR.Remove(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult DuyuruGuncelle(int id)
        {
            var x = db.TBL_DUYURULAR.Find(id);
            //var d = Convert.ToDateTime(x.Tarih).ToShortDateString();
            //ViewBag.date1 = d;
            return View(x);
        }
        [HttpPost]
        public ActionResult DuyuruGuncelle(TBL_DUYURULAR p )
        {
            var x = db.TBL_DUYURULAR.Find(p.id);
            x.icerik = p.icerik;
            x.Kategori = p.Kategori;
            x.Tarih = p.Tarih;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC5-Proje1/Views/Duyuru/DuyuruDetay.cshtml
@model MVC5_Proje1.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>@ViewBag.d1</h2>
<br />
<p>@ViewBag.d2</p>

MVC5-Proje1/Views/Duyuru/DuyuruEkle.cshtml
@model MVC5_Proje1.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruEkle";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Duyuru Ekle</h2>
<br />
<form class="form-group" method="post">
    <div>
        <label>Konu</label>
        @Html.TextBoxFor(k => k.Kategori, new { @class = "form-control" }) <br />
    </div>
    <div>
        <label>İçerik</label>
        @Html.TextBoxFor(k => k.icerik, new { @class = "form-control" }) <br />
    </div>
    <div>
        <label>Tarih</label>
        @Html.TextBoxFor(k => k.Tarih, new { @class = "form-control" }) <br />
    </div>
    <div>
        <button class="btn btn-primary"> Duyuru EKle </button>
    </div>
</form>

MVC5-Proje1/Views/Duyuru/DuyuruGuncelle.cshtml
@model MVC5_Proje1.Models.Entity.TBL_DUYURULAR
@{
    ViewBag.Title = "DuyuruGuncelle";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>Duyuru Güncelle</h2>

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div>
        <div>
            <label>Konu</label>
            @Html.TextBoxFor(x => x.Kategori, new { @class = "form-control" }) <br />
        </div>
        <div>
            <label>İçerik</label>
            @Html.TextAreaFor(x => x.icerik, new { @class = "form-control" })<br />
        </div>
        <div>
            <label>Tarih</label>
            @Html.TextBoxFor(x=>x.Tarih , new { @class = "form-control" })<br />
        </div>
        <button class="btn btn-primary">Duyuruyu Güncelle</button>
    </div>
}

MVC5-Proje1/Views/Duyuru/Index.cshtml
@using MVC5_Proje1.Models.Entity
@model List<TBL_DUYURULAR>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<h2>DUYURU SAYFASI</h2>

<table class="table table-bordered">
    <th>İçerik</th>
    <th>İşlem</th>

    @foreach (var x in Model)
    {
        <tr>
            <td>
                <div class="media">
                    <div class="media-left media-top">
                        <img class="media-object" style="width:60px" src="~/admin.jfif">
                    </div>
                    <div class="media-body">
                        @Convert.ToDateTime(x.Tarih).ToString("dd/MM/yyyy")
                       <b><br/><a href="/Duyuru/DuyuruDetay/@x.id" style="color:#363636">@x.Kategori</a></b>
                    </div>
                </div>
            </td>
            <td><a href="/Duyuru/DuyuruGuncelle/@x.id" class="btn btn-primary">Güncelle</a></td>
            <td><a href="/Duyuru/DuyuruSil/@x.id" class="btn btn-danger">Sil</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/DuyuruEkle" class="btn btn-primary">Duyuru Ekle</a>